import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableRow,
  TableCell,
  TextRun,
  WidthType,
  AlignmentType,
  BorderStyle,
  HeadingLevel,
  ShadingType,
} from "docx";
import type { FormField } from "@/lib/ai/analyze-form";

const BRAND_COLOR = "2563EB"; // blue-600

/**
 * Generates a structured .docx document listing all filled form fields
 * in a two-column table (Field Name | Value) with FormPilot branding.
 * Used for all source types including Word forms.
 */
export async function generateStructuredDocx(
  title: string,
  fields: FormField[]
): Promise<Buffer> {
  const filledFields = fields.filter((f) => f.value);
  const allFields = fields; // include empty fields as blank rows

  const tableRows: TableRow[] = [
    // Header row
    new TableRow({
      tableHeader: true,
      children: [
        new TableCell({
          width: { size: 45, type: WidthType.PERCENTAGE },
          shading: { type: ShadingType.SOLID, color: BRAND_COLOR, fill: BRAND_COLOR },
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "Field", bold: true, color: "FFFFFF", size: 20 }),
              ],
            }),
          ],
        }),
        new TableCell({
          width: { size: 55, type: WidthType.PERCENTAGE },
          shading: { type: ShadingType.SOLID, color: BRAND_COLOR, fill: BRAND_COLOR },
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: "Value", bold: true, color: "FFFFFF", size: 20 }),
              ],
            }),
          ],
        }),
      ],
    }),
    // Data rows
    ...allFields.map(
      (f) =>
        new TableRow({
          children: [
            new TableCell({
              width: { size: 45, type: WidthType.PERCENTAGE },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: f.label + (f.required ? " *" : ""),
                      bold: !!f.required,
                      size: 20,
                    }),
                  ],
                }),
              ],
            }),
            new TableCell({
              width: { size: 55, type: WidthType.PERCENTAGE },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: f.value ?? "",
                      size: 20,
                      color: f.value ? "1E293B" : "94A3B8",
                      italics: !f.value,
                    }),
                  ],
                }),
              ],
            }),
          ],
        })
    ),
  ];

  const exportedAt = new Date().toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [
              new TextRun({ text: title, bold: true, size: 28, color: BRAND_COLOR }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Exported via FormPilot · ${exportedAt} · ${filledFields.length}/${fields.length} fields filled`,
                size: 18,
                color: "64748B",
              }),
            ],
          }),
          new Paragraph({ text: "" }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: {
              top: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
              bottom: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
              left: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
              right: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
            },
            rows: tableRows,
          }),
          new Paragraph({ text: "" }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: "Generated by FormPilot — getformpilot.com",
                size: 16,
                color: "94A3B8",
                italics: true,
              }),
            ],
          }),
        ],
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
